In [13]:
import numpy as np
import pandas as pd

num_students = 1000
max_rank = 25

gpa = np.clip(np.random.normal(3.5, 0.5, num_students), 0, 4)
sat_score = np.clip(800 + 200 * (gpa - 2) + np.random.normal(0, 100, num_students), 400, 1600)

students = pd.DataFrame({
    "Student_ID": range(1, num_students + 1),
    "GPA": gpa.round(2),
    "SAT_Score": sat_score.round(0),
})

students["Class_Rank"] = students["GPA"].rank(method="dense", ascending=False).astype(int)

students.to_csv("StudentAdmissionData1.csv", index=False)
print(students)


     Student_ID   GPA  SAT_Score  Class_Rank
0             1  3.02      959.0          99
1             2  3.32     1007.0          69
2             3  3.42      976.0          59
3             4  3.47     1147.0          54
4             5  2.91     1057.0         110
5             6  3.04      959.0          97
6             7  3.92     1110.0           9
7             8  3.25     1097.0          76
8             9  3.71     1134.0          30
9            10  3.90     1384.0          11
10           11  3.11      994.0          90
11           12  3.87     1297.0          14
12           13  3.15      979.0          86
13           14  4.00     1106.0           1
14           15  4.00     1240.0           1
15           16  4.00     1094.0           1
16           17  3.85     1268.0          16
17           18  3.19     1202.0          82
18           19  4.00     1128.0           1
19           20  3.20     1096.0          81
20           21  3.64     1171.0          37
21        

In [1]:
import numpy as np
import pandas as pd

random_data = np.zeros((1000, 3))

# populate arrays
random_data[:, 0] = np.round(np.random.uniform(0.0, 4.0, 1000), 2)
random_data[:, 1] = np.random.randint(400, 1601, 1000)
random_data[:, 2] = np.random.randint(1, 26, 1000)

# preprocess
random_data = random_data.astype(object)
random_data[:, 1] = random_data[:, 1].astype(int)
random_data[:, 2] = random_data[:, 2].astype(int)

df = pd.DataFrame()

# populate the dataframe
df["GPA"] = random_data[:, 0]
df["satScore"] = random_data[:, 1]
df["Rank"] = random_data[:, 2]

print(random_data[:10])
df.head()

df.to_csv("StudentAdmissionData.csv", index=False)

[[1.37 967 12]
 [2.06 491 5]
 [2.6 534 20]
 [0.21 694 23]
 [0.61 1148 12]
 [3.4 1301 15]
 [3.93 1255 22]
 [3.32 478 2]
 [1.09 1505 13]
 [3.97 619 25]]


In [12]:
import numpy as np
import pandas as pd

# Parameters
num_students = 1000
max_rank = 25  # Maximum rank

# Simulate GPAs
gpa = np.clip(np.random.normal(3.5, 0.5, num_students), 0, 4)

# Simulate SAT scores
sat_score = np.clip(800 + 200 * (gpa - 1) + np.random.normal(0, 150, num_students), 400, 1600)

# Create DataFrame
students = pd.DataFrame({
    "Student_ID": range(1, num_students + 1),  # Ensure this matches num_students
    "GPA": gpa.round(2)  # Ensure GPA is rounded
})

# Create a DataFrame
students = pd.DataFrame({
    "GPA": gpa.round(2),
    "SAT_Score": sat_score.round(0),
})

# Rank students by GPA (higher GPA gets better rank)
students["Class_Rank"] = students["GPA"].rank(method="dense", ascending=False).astype(int)
pd.set_option('display.max_rows', None)
print(students)

students.to_csv("StudentAdmissionData2.csv", index=False)

      GPA  SAT_Score  Class_Rank
0    3.14     1485.0          87
1    4.00     1353.0           1
2    3.69     1335.0          32
3    3.03     1096.0          98
4    2.60     1096.0         138
5    3.21     1317.0          80
6    3.61     1113.0          40
7    3.53     1363.0          48
8    2.99     1230.0         102
9    3.87     1314.0          14
10   4.00     1208.0           1
11   3.74     1249.0          27
12   3.86     1170.0          15
13   2.93     1143.0         108
14   4.00     1499.0           1
15   3.75     1600.0          26
16   3.14     1111.0          87
17   3.18     1250.0          83
18   4.00     1580.0           1
19   4.00     1401.0           1
20   3.45     1110.0          56
21   3.38     1282.0          63
22   4.00     1494.0           1
23   3.06     1226.0          95
24   4.00     1588.0           1
25   3.94     1367.0           7
26   4.00     1600.0           1
27   3.36     1167.0          65
28   3.32     1314.0          69
29   3.93 

In [3]:
import numpy as np
import pandas as pd

data = np.zeros((1000, 20), dtype=int)

for i in range(data.shape[0]):
    positions = np.random.choice(20, 3, replace=False)
    data[i, positions[0]] = 1
    data[i, positions[1]] = 2
    data[i, positions[2]] = 3

columns = [f"pref{i+1}" for i in range(20)]
df = pd.DataFrame(data, columns=columns)

df.to_csv("StudentPrefData.csv", index=False)

print(data[:10])
print(df.head())

[[0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 1 0 2 0 0]
 [0 0 0 0 0 0 1 0 2 0 0 0 3 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 1 3]
 [0 0 0 3 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 1]
 [0 0 1 2 0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0]
 [0 0 0 0 3 0 0 0 0 0 0 1 0 2 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 2 0 0 0 0 0 0 0 3 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 2 0 1 0 0 0 3 0]
 [1 0 0 0 0 0 0 0 0 3 0 0 2 0 0 0 0 0 0 0]
 [2 0 0 0 0 0 0 0 0 0 0 0 3 0 1 0 0 0 0 0]]
   pref1  pref2  pref3  pref4  pref5  pref6  pref7  pref8  pref9  pref10  \
0      0      0      0      0      0      0      0      0      0       0   
1      0      0      0      0      0      0      1      0      2       0   
2      0      0      0      0      0      0      0      0      0       0   
3      0      0      0      3      0      0      0      0      0       0   
4      0      0      1      2      0      0      0      0      0       0   

   pref11  pref12  pref13  pref14  pref15  pref16  pref17  pref18  pref19  \
0       0       0       0       3  