In [1]:
import numpy as np
import pandas as pd

random_data = np.zeros((1000, 3))

# populate arrays
random_data[:, 0] = np.round(np.random.uniform(0.0, 4.0, 1000), 2)
random_data[:, 1] = np.random.randint(400, 1601, 1000)
random_data[:, 2] = np.random.randint(1, 26, 1000)

# preprocess
random_data = random_data.astype(object)
random_data[:, 1] = random_data[:, 1].astype(int)
random_data[:, 2] = random_data[:, 2].astype(int)

df = pd.DataFrame()

# populate the dataframe
df["GPA"] = random_data[:, 0]
df["satScore"] = random_data[:, 1]
df["Rank"] = random_data[:, 2]

print(random_data[:10])
df.head()

df.to_csv("StudentAdmissionData.csv", index=False)

[[1.37 967 12]
 [2.06 491 5]
 [2.6 534 20]
 [0.21 694 23]
 [0.61 1148 12]
 [3.4 1301 15]
 [3.93 1255 22]
 [3.32 478 2]
 [1.09 1505 13]
 [3.97 619 25]]


In [3]:
import numpy as np
import pandas as pd

data = np.zeros((1000, 20), dtype=int)

for i in range(data.shape[0]):
    positions = np.random.choice(20, 3, replace=False)
    data[i, positions[0]] = 1
    data[i, positions[1]] = 2
    data[i, positions[2]] = 3

columns = [f"pref{i+1}" for i in range(20)]
df = pd.DataFrame(data, columns=columns)

df.to_csv("StudentPrefData.csv", index=False)

print(data[:10])
print(df.head())

[[0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 1 0 2 0 0]
 [0 0 0 0 0 0 1 0 2 0 0 0 3 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 1 3]
 [0 0 0 3 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 1]
 [0 0 1 2 0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0]
 [0 0 0 0 3 0 0 0 0 0 0 1 0 2 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 2 0 0 0 0 0 0 0 3 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 2 0 1 0 0 0 3 0]
 [1 0 0 0 0 0 0 0 0 3 0 0 2 0 0 0 0 0 0 0]
 [2 0 0 0 0 0 0 0 0 0 0 0 3 0 1 0 0 0 0 0]]
   pref1  pref2  pref3  pref4  pref5  pref6  pref7  pref8  pref9  pref10  \
0      0      0      0      0      0      0      0      0      0       0   
1      0      0      0      0      0      0      1      0      2       0   
2      0      0      0      0      0      0      0      0      0       0   
3      0      0      0      3      0      0      0      0      0       0   
4      0      0      1      2      0      0      0      0      0       0   

   pref11  pref12  pref13  pref14  pref15  pref16  pref17  pref18  pref19  \
0       0       0       0       3  